dist: trusty
sudo: false

before_install:
    - df -h
    - cd /dev/xvdb
    - ls
    - mkdir cm
    - cp -a /home/travis/cm /etc/hosts/cm
    - PATH=/home/travis/bin:$PATH
    - curl https://storage.googleapis.com/git-repo-downloads/repo > /home/travis/bin/repo
    - chmod a+x ~/bin/repo
    - git config --global color.ui true
    - cd /home/travis/cm && repo init -u git://github.com/LineageOS/android.git -b cm-14.1
    
script:
    - repo sync
    - source build/envsetup.sh
    - lunch lineage_bacon
    - mka bacon
